platform.dts: Fix preprocessor bodging prop name
As Clang defines the C preprocessor macro `linux` as `1`, the following
property was incorrectly renamed in the preprocessed platform.dts:

  /chosen/linux,pci-probe-only --> /chosen/1,pci-probe-only

before being passed to DTC. The macro itself is <built-in>:

  error: 'linux' macro redefined [-Werror,-Wmacro-redefined]
     52 | #define linux
        |         ^
  <built-in>:474:9: note: previous definition is here
    474 | #define linux 1
        |         ^

Therefore, undefine it from the .dts, to prevent the substitution.

Bug: 376119598
Test: m pvmfw_platform.dts.preprocessed
Change-Id: I76e4e1c615bed55665089a6ab539a688fe4355e5